---
title: "14_aaa"
author: "Léa Bouchet"
date: "2024-06-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(flextable)
library(ggthemes)
library(tidyverse)
library(aspe)
library(ggplot2)
library (khroma)
library(dplyr)
library(wesanderson)
library(zoo)
library(gt)
library(lemon)
library(trend)
library(ggh4x)
library(purrr)
library(broom)
library(ggforce)
```

```{r Chargement des données}
## Chargement des données 
load(file = "../processed_data/calcul_indicateurs_regionaux.rda")
load(file = "../processed_data/mann_kendall_tendances.rda")
load(file = "../processed_data/glm_lm_tendances.rda")
```





Générer des graphiques : 

```{r}
generate_graph <- function(data, 
                           esp_code_alternatif, 
                           indicateur, 
                           stade) {
  ggplot(data %>% 
           filter(esp_code_alternatif == !!esp_code_alternatif,
                  indicateur == !!indicateur,
                  stade == !!stade), 
         aes(x = annee, y = valeur, group = stade, color = stade)) +
    geom_point(shape = 1) +
    geom_smooth(method = "loess", se = FALSE) +
    scale_color_manual(values = c("juv" = "#92D080", "ad" = "#A97B30", "ind" = "black"),
                       name = "Stade", labels = c("Adulte", "Indifférencié", "Juvénile")) +
    labs(x = "Années", y = "Valeurs") +
    theme_bw() +
    theme(strip.background = element_rect(color = "black", fill = "#faffff"),
          legend.position = "bottom",
          panel.background = element_rect(fill = "#faf0e0"),
          panel.grid.major = element_line(color = "lightgrey", size = 0.1),
          panel.grid.minor = element_line(color = "lightgrey"),
          axis.text.x = element_text(angle = 45))
}
```


```{r}
# Spécifiez le répertoire de sauvegarde
output_dir <- "../assets/graph_esp_indicateur" 
```



```{r}
# Sauvegarder les graphiques dans des fichiers avec stades spécifiques pour chaque indicateur

reg_indicateur_red <- reg_indicateur %>% 
  filter(esp_code_alternatif %in% c("ANG","BRO", "CHA", "CHE",
                                    "PER", "GAR", "GOU", "LOF", "LPP",
                                    "SAT", "TRF", "VAI", "VAR"))


# Initialisation d'une liste pour stocker les informations de chaque graphique
graph_info <- list()

for (esp in unique(reg_indicateur_red$esp_code_alternatif)) {
  for (ind in c("densite_surface", "taux_occurrence", "pourcentage_juveniles")) {
    stade_sel <- ifelse(ind == "densite_surface", 
                        "ad", 
                        "ind")
    
    p <- generate_graph(reg_indicateur, 
                        esp, 
                        ind,
                        stade_sel)
    
    filename <- paste0("graph_", esp, "_", ind, ".png")
    
    filepath <- file.path(output_dir, filename)
    ggsave(filename = filepath, plot = p, width = 5, height = 4)
    
    graph_info[[length(graph_info) + 1]] <- list(esp_code_alternatif = esp,
                                                 indicateur = ind,
                                                 graphique_tendance = filepath)
    

  }
}

```

Création d'un dataframe qui va pourvoir contenir toutes les bonnes informations : 

D'abord application pour les glm : 

```{r}

# Définir une fonction pour déterminer la tendance
determine_trend <- function(row) {
  ifelse(grepl("\\*", row$sig), 
         ifelse(row$Estimate > 0, "Increase", 
                ifelse(row$Estimate < 0, "Decrease", NA)), 
         "No trend")
}

# Ajouter la colonne "trend" en utilisant la fonction determine_trend
glm_lm_resultats <- glm_lm_resultats %>%
  mutate(trend = determine_trend(.))

tab_recap_glm <- glm_lm_resultats %>% #(nous on veut que l'année en plus)
  select(esp_code_alternatif,
         indicateur,
         stade,
         trend,
         sig,
         periode,
         row_name) %>% 
    filter(!stade == "juv",
           row_name == "annee",
         indicateur %in% c("densite_surface", "pourcentage_juveniles", "taux_occurrence"),
         !(indicateur == "densite_surface" & stade != "ad")) %>% 
  select(-row_name) %>% 
  mutate(tab = "tab_glm")


```

Puis application pour les mk_st : 

```{r}
tab_recap_mk <- bind_rows(mk_st_by_group_resultats)

tab_recap_mk <- tab_recap_mk %>% 
    select(esp_code_alternatif,
         indicateur,
         stade,
         trend,
         sig,
         periode) %>% 
    filter(!stade == "juv",
         indicateur %in% c("densite_surface", "pourcentage_juveniles", "taux_occurrence"),
         !(indicateur == "densite_surface" & stade != "ad")) %>% 
  mutate(tab = "tab_mk")
```

On a maintenant toutes les info pour faire une version finale du tableau :


```{r}
tab_final_glm_mk <- bind_rows(tab_recap_glm,
                              tab_recap_mk)
```

