---
title: "Liste Rouge Régionale des poissons d'eau douce de Bretagne"
subtitle: "Tableau Tendances Temporelles"
author: "OFB Bretagne"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```


# Installation 

## Chargement des packages, fonctions et des données 

```{r Chargement des packages}
## Chargement des packages ----
library(ggthemes)
library(tidyverse)
library(kableExtra)
library(readxl)
```

```{r}
load(file = "../processed_data/mk_glmm_lm_tendances.rda")
mod_bay <- read_excel("../raw_data/mod_bay.xlsx")
```


## Pour les données indifférenciées

```{r}
rownames(glmm_resultats) <- seq_len(nrow(glmm_resultats))
```


```{r, fig.height = 8, fig.width = 10}
# Joindre les DataFrames sur les colonnes communes
df_combined <- reg_indicateur_lrr_tendances_lm %>%
  filter(indicateur == "densite_surface") %>% 
  rename(trend_lm = trend, 
         sig_lm = sig) %>%
  left_join(glmm_resultats %>% 
              select(esp_code_alternatif,
                     indicateur,
                     trend,
                     sig) %>% 
              rename(trend_glmm = trend, 
                     sig_glmm = sig), 
            by = c("esp_code_alternatif", "indicateur")) %>%
  left_join(reg_indicateur_lrr_tendances_mk_st %>% 
              select(esp_code_alternatif,
                     indicateur,
                     trend,
                     sig) %>% 
              rename(trend_mk_st = trend, sig_mk_st = sig), 
            by = c("esp_code_alternatif", "indicateur"))
```


```{r, fig.height = 8, fig.width = 10}
# Sélectionner les colonnes à afficher
df_final <- df_combined %>%
  select(esp_code_alternatif, 
         periode, 
         indicateur, 
         trend_lm, 
         sig_lm,
         trend_mk_st,
         sig_mk_st,
         trend_glmm,
         sig_glmm
         ) %>% 
  arrange(periode,
          esp_code_alternatif)
```


```{r, fig.height = 8, fig.width = 10}
df_final1 <- df_final %>% 
  left_join(mod_bay) %>% 
  mutate_all(~ replace_na(., " "))
```


```{r, fig.height = 8, fig.width = 10}
colnames(df_final1)[1:11] <- c("Code espèce", "Période", "Indicateur", "Linéaire", " ", "MK / ST", " ", "GLMM", " ", "Bayésien", "")

d <- kable(df_final1,
      booktabs = TRUE,
      escape = FALSE,
      align = c("l", "l", "l", "c", "l", "c", "l", "c", "l", "c", "l")) %>%
  add_header_above(c(" " = 3, "Tendances temporelles" = 8)) %>%
  column_spec(3, italic = TRUE) %>% 
  kable_styling(full_width = FALSE, position = "left") %>% 
  collapse_rows(columns = 1:2:3)

d
```







## Pour les données qui ne concernent que les adultes : 






